baseURL: https://ongonf.github.io/hugodemo
languageCode: en-gb
title: My Site Title
theme: govukhugo
publishDir: public
canonifyurls: true

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  govuk: false
  logotext: ABC
  product: Product Name
  phase: alpha
  feedbackurl: https://your.site/feedback/
